/**
 * The Store entity factory (core/store.js).
 *
 * `courses`, `events`, `lessons`, `readings` and `documents` are generated by
 * one `makeEntity` factory, so they should honour one create/update/remove
 * contract and emit one `change` event per mutation. These tests assert the
 * contract through each namespace's public verbs.
 */
import { describe, it, expect, beforeEach } from "vitest";
import { Store } from "../../src/core/store.js";

const ENTITIES = ["courses", "events", "lessons", "readings", "documents"];

beforeEach(() => {
  Store.resetAll();
});

describe.each(ENTITIES)("Store.%s", (name) => {
  it("creates, updates and removes through one contract", () => {
    const ns = Store[name];
    const changes = [];
    const off = Store.on("change", (c) => changes.push(c));
    const id = name + "-1";

    const created = ns.save({ id });
    expect(created.id).toBe(id);
    expect(ns.get(id)).toBe(created);
    expect(ns.all().some((x) => x.id === id)).toBe(true);

    // Updating by id returns the same record, mutated in place.
    const updated = ns.save({ id, marker: "x" });
    expect(updated).toBe(created);
    expect(updated.marker).toBe("x");

    expect(ns.remove(id)).toBe(true);
    expect(ns.get(id)).toBe(null);
    expect(ns.all().some((x) => x.id === id)).toBe(false);

    expect(changes.map((c) => c.op)).toEqual(["insert", "update", "remove"]);
    expect(changes.every((c) => c.entity === name)).toBe(true);
    off();
  });
});

describe("cascades", () => {
  it("documents.remove drops only that document's chunks", () => {
    Store.db.chunks = [
      { id: "d1#0", docId: "d1" },
      { id: "d2#0", docId: "d2" },
    ];

    Store.documents.remove("d1");

    expect(Store.db.chunks.map((c) => c.id)).toEqual(["d2#0"]);
  });

  it("events.remove prunes plan blocks for that event", () => {
    Store.db.plan = [
      { id: "p1", eventId: "e1" },
      { id: "p2", eventId: "e2" },
    ];

    Store.events.remove("e1");

    expect(Store.db.plan.map((p) => p.id)).toEqual(["p2"]);
  });
});
